name: projecteuromedflutter
description: "A new Flutter project."
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0" # Adjusted SDK version

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.0.7  # New line added for shared_preferences

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/uemf_app.jpg"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
